*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jan 15 15:00:01 2021] ***
compiled with version: 7.5.0 on 21 July 2020 01:36:53
os: Linux-4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018
nodename: python
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/ubuntu/Desktop/44/shunyi_44_meiduo_cangku/meiduo_mall
writing pidfile to uwsgi.pid
detected binary path: /home/ubuntu/.virtualenvs/py3_shunyi_44/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ubuntu/Desktop/44/shunyi_44_meiduo_cangku/meiduo_mall
your processes number limit is 30823
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 192.168.19.128:8001 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:39563 (port auto-assigned) fd 3
Python version: 3.6.9 (default, Apr 18 2020, 01:56:04)  [GCC 8.4.0]
Set PythonHome to /home/ubuntu/.virtualenvs/py3_shunyi_44
Python main interpreter initialized at 0x555b1367c0f0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x555b1367c0f0 pid: 28438 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28438)
spawned uWSGI worker 1 (pid: 28442, cores: 2)
spawned uWSGI worker 2 (pid: 28444, cores: 2)
spawned uWSGI worker 3 (pid: 28446, cores: 2)
spawned uWSGI worker 4 (pid: 28448, cores: 2)
spawned uWSGI http 1 (pid: 28450)
ERROR exception 77 Invalid HTTP_HOST header: '192.168.19.128:8001'. You may need to add '192.168.19.128' to ALLOWED_HOSTS.
WARNING log 228 Bad Request: /areas/
[pid: 28448|app: 0|req: 1/1] 192.168.19.128 () {38 vars in 689 bytes} [Fri Jan 15 07:00:04 2021] GET /areas/ => generated 61479 bytes in 665 msecs (HTTP/1.1 400) 2 headers in 67 bytes (1 switches on core 0)
ERROR exception 77 Invalid HTTP_HOST header: '192.168.19.128:8001'. You may need to add '192.168.19.128' to ALLOWED_HOSTS.
WARNING log 228 Bad Request: /favicon.ico
[pid: 28442|app: 0|req: 1/2] 192.168.19.128 () {40 vars in 656 bytes} [Fri Jan 15 07:00:05 2021] GET /favicon.ico => generated 61600 bytes in 489 msecs (HTTP/1.1 400) 2 headers in 67 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 28450)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jan 15 15:03:10 2021] ***
compiled with version: 7.5.0 on 21 July 2020 01:36:53
os: Linux-4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018
nodename: python
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/ubuntu/Desktop/44/shunyi_44_meiduo_cangku/meiduo_mall
writing pidfile to uwsgi.pid
detected binary path: /home/ubuntu/.virtualenvs/py3_shunyi_44/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ubuntu/Desktop/44/shunyi_44_meiduo_cangku/meiduo_mall
your processes number limit is 30823
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 192.168.19.128:8001 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:42637 (port auto-assigned) fd 3
Python version: 3.6.9 (default, Apr 18 2020, 01:56:04)  [GCC 8.4.0]
Set PythonHome to /home/ubuntu/.virtualenvs/py3_shunyi_44
Python main interpreter initialized at 0x55a667fb60f0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55a667fb60f0 pid: 28605 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28605)
spawned uWSGI worker 1 (pid: 28608, cores: 2)
spawned uWSGI worker 2 (pid: 28610, cores: 2)
spawned uWSGI worker 3 (pid: 28612, cores: 2)
spawned uWSGI worker 4 (pid: 28614, cores: 2)
spawned uWSGI http 1 (pid: 28615)
[pid: 28614|app: 0|req: 1/1] 192.168.19.128 () {38 vars in 689 bytes} [Fri Jan 15 07:03:13 2021] GET /areas/ => generated 1772 bytes in 516 msecs (HTTP/1.1 200) 4 headers in 116 bytes (1 switches on core 0)
WARNING log 228 Not Found: /favicon.ico
[pid: 28614|app: 0|req: 2/2] 192.168.19.128 () {40 vars in 656 bytes} [Fri Jan 15 07:03:13 2021] GET /favicon.ico => generated 6231 bytes in 38 msecs (HTTP/1.1 404) 4 headers in 116 bytes (1 switches on core 1)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 28615)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
